export default {
  app: {
    name: 'Zealous-admin',
    version: '1.0.0',
    logo: '/logo.svg',
    storagePrefix: 'zealous-admin-',
    storageType: 'local',
    styleClassNamePrefix: 'zealous-admin',
    isEnableMemory: true,
    isEnableMobileAccess: true,
    isEnableDynamicTitle: true,
    isEnableMourningMode: false,
    isEnableWatermark: false,
    account: {
      isEnablePermission: true,
      isEnableMultiAccount: false,
      expireMode: 'logout',
    },
    layout: {
      isCenter: false,
      layoutScope: 'outside',
      width: 1200,
    },
    homePage: {
      isEnableHomePage: true,
      title: '主页',
    },
    copyright: {
      isEnableCopyright: true,
      date: '2024',
      company: 'Zealous-admin',
      website: 'https://github.com/zealous-admin',
    },
  },
  theme: {
    themeColor: '#1677ff',
    darkMode: 'auto',
    compactMode: false,
    colorWeak: false,
    happyEffect: false,
  },
  menu: {
    menuType: 'head',
    menuFillStyle: 'radius',
    menuActiveStyle: 'none',
    subMenuUniqueOpened: true,
    subMenuCollapse: false,
    isEnableSubMenuCollapse: true,
  },
  page: {
    isEnableTransition: true,
    transitionType: 'fade-in',
    isEnablePageLoadProgress: true,
  },
  topBar: {
    order: ['TabBar', 'ToolBar'],
    position: 'static',
    tabBar: {
      isEnableTabBar: true,
      style: 'default',
      widthType: 'auto',
      width: '100%',
      showIcon: true,
      dblClickEvent: 'refresh',
    },
    toolbar: {
      isEnableToolbar: true,
      breadcrumb: {
        isEnableBreadcrumb: true,
        style: 'modern',
        isEnableMainNav: true,
      },
      isEnableSearch: true,
      isEnableI18n: true,
      isEnablePageReload: true,
      isEnableFullscreen: true,
      isEnableTheme: true,
      toolbarOrder: ['Breadcrumb', 'Search', 'I18n', 'PageReload', 'Fullscreen', 'Theme'],
    },
  },
}
